### ISSUE TITLE
INI File errors

### ISSUE THREAD

**Issue by HaoZeke** [piotrmurach/tty-config#14]
### Describe the problem

Can't seem to read an INI file.

### Steps to reproduce the problem

```ini
[Main]
job = saddle_search
temperature = 300
random_seed = 706253457

[Potential]
potential = ams
```

With the code:

```ruby
require 'tty-config'
config = TTY::Config.new
config.read("#{Dir.pwd}/config.ini", format: :ini)
```

### Actual behaviour

Output:

```bash
Traceback (most recent call last):
	4: from $HOME/Git/Github/CPP/EONgit/tools/gprdimer/eonc.rb:49:in `<main>'
	3: from $HOME/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/tty-config-0.5.0/lib/tty/config.rb:470:in `read'
	2: from $HOME/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/tty-config-0.5.0/lib/tty/config.rb:830:in `unmarshal'
	1: from $HOME/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/tty-config-0.5.0/lib/tty/config/marshallers/ini_marshaller.rb:26:in `unmarshal'
$HOME/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/tty-config-0.5.0/lib/tty/config/marshallers/ini_marshaller.rb:26:in `merge!': no implicit conversion of nil into Hash (TypeError)
```
### Expected behaviour

What did you expect to happen?

### Describe your environment

* OS version: MacOS (but also tested on Linux)
* Ruby version: 2.7.3
* TTY::Config version: tty-config (0.5.0)

**Comment by piotrmurach** [comment]
Hi Rohit,

Thanks for reporting this issue and providing steps to reproduce this bug.

As it turned out the INI file marshaller didn't account for configuration without global properties.

Would you have time to check this fix? I'll make a release shortly.

**Comment by piotrmurach** [comment]
@HaoZeke Released `v0.5.1` with the fix.

**Comment by HaoZeke** [comment]
@piotrmurach thanks so much, sorry I wasn't able to respond earlier.
