### ISSUE TITLE
Can't read new config file

### ISSUE THREAD

**Issue by Cyraus** [piotrmurach/tty-config#9]
When I use `FileUtils.touch` to create a new config file (empty yaml file) in specified directory and read it, I got an error:
```
3: from /usr/lib/ruby/gems/2.6.0/gems/tty-config-0.3.1/lib/tty/config.rb:393:in `read'
2: from /usr/lib/ruby/gems/2.6.0/gems/tty-config-0.3.1/lib/tty/config.rb:273:in `merge'
1: from /usr/lib/ruby/gems/2.6.0/gems/tty-config-0.3.1/lib/tty/config.rb:559:in `deep_merge'
/usr/lib/ruby/gems/2.6.0/gems/tty-config-0.3.1/lib/tty/config.rb:559:in `merge': no implicit conversion of nil into Hash (TypeError)
```

**Comment by piotrmurach** [comment]
Released `v0.3.2` with a fix.
